### ISSUE TITLE
Sugestões de ferramentas para construções de APIs

### ISSUE THREAD

**Issue by AirckLima** [astromar2187/projeto1#1]
# Next JS + Prisma ORM
Apesar de ser uma framework React, o Next tem a funcionalidade de **Route Handlers** que em conjunto com a estrutura de rotas baseadas em diretórios fica bem fácil de criar uma API Rest. Já o prisma é para acessar e até mesmo gerar as tabelas do banco de dados pensando nelas como objetos javascript.

# Strapi
essa eu acho a opção mais overpower já que o strapi é um Headless CMS que cria uma API Rest (suporte para GraphQL através de plugin) utilizando uma interface visual, podendo criar os tipos de conteúdo apenas selecionando os campos e tipos de dados, além de adicionar restrições de regras de negócio e fazer extensões de criação utilizando os controllers. Pelo fato de ser Headless CMS permite a criação de interfaces visuais utilizando as ferramentas que quiser.

**Comment by AirckLima** [comment]
# FastAPI
Essa opção eu não cheguei a usar, mas é uma opção para fazer o projeto em Python, mas pelo que pesquisei, ele não oferece opções de acesso a bancos.

**Comment by astromar2187** [comment]
Bom dia, Airck! Muito obrigada pelas recomendações, usarei Fast mesmo no
back, e uma amiga fará o front, mas não sei ainda qual ferramenta ela vai
usar. Alguma recomendação de projetos para desenvolver as habilidades em
Fast?
Att.

**Comment by AirckLima** [comment]
Como eu disse, eu não tenho experiência no FastAPI mas imagino que isso pode ajudar
- https://github.com/mjhea0/awesome-fastapi
- https://fastapi.tiangolo.com/project-generation/
- https://dev.to/snlucas/starting-with-fastapi-creating-a-super-simple-crud-exercise-37a0
- https://github.com/emerymoriconi/fastapi (projeto de uma colega de curso sua)

**Comment by astromar2187** [comment]
Muito obrigado pela indicação.
